// Country list for address forms - streamlined for English-speaking markets

export interface Country {
  value: string;
  label: string;
  continent: string;
}

export const COUNTRIES: Country[] = [
  // PRIMARY ENGLISH-SPEAKING COUNTRIES
  { value: "US", label: "United States", continent: "Primary English-Speaking" },
  { value: "GB", label: "United Kingdom", continent: "Primary English-Speaking" },
  { value: "CA", label: "Canada", continent: "Primary English-Speaking" },
  { value: "AU", label: "Australia", continent: "Primary English-Speaking" },
  { value: "NZ", label: "New Zealand", continent: "Primary English-Speaking" },
  { value: "IE", label: "Ireland", continent: "Primary English-Speaking" },
  { value: "ZA", label: "South Africa", continent: "Primary English-Speaking" },

  // LARGE ENGLISH-SPEAKING POPULATIONS
  { value: "IN", label: "India", continent: "Large English-Speaking Population" },
  { value: "PH", label: "Philippines", continent: "Large English-Speaking Population" },
  { value: "NG", label: "Nigeria", continent: "Large English-Speaking Population" },
  { value: "PK", label: "Pakistan", continent: "Large English-Speaking Population" },
  { value: "SG", label: "Singapore", continent: "Large English-Speaking Population" },
  { value: "MY", label: "Malaysia", continent: "Large English-Speaking Population" },
  { value: "HK", label: "Hong Kong", continent: "Large English-Speaking Population" },
  { value: "KE", label: "Kenya", continent: "Large English-Speaking Population" },
  { value: "GH", label: "Ghana", continent: "Large English-Speaking Population" },

  // MAJOR EUROPEAN MARKETS
  { value: "DE", label: "Germany", continent: "Major European Markets" },
  { value: "FR", label: "France", continent: "Major European Markets" },
  { value: "ES", label: "Spain", continent: "Major European Markets" },
  { value: "IT", label: "Italy", continent: "Major European Markets" },
  { value: "NL", label: "Netherlands", continent: "Major European Markets" },
  { value: "SE", label: "Sweden", continent: "Major European Markets" },
  { value: "NO", label: "Norway", continent: "Major European Markets" },
  { value: "DK", label: "Denmark", continent: "Major European Markets" },
  { value: "FI", label: "Finland", continent: "Major European Markets" },
  { value: "CH", label: "Switzerland", continent: "Major European Markets" },
  { value: "AT", label: "Austria", continent: "Major European Markets" },
  { value: "BE", label: "Belgium", continent: "Major European Markets" },
  { value: "PT", label: "Portugal", continent: "Major European Markets" },

  // MAJOR ASIAN MARKETS
  { value: "JP", label: "Japan", continent: "Major Asian Markets" },
  { value: "KR", label: "South Korea", continent: "Major Asian Markets" },
  { value: "CN", label: "China", continent: "Major Asian Markets" },
  { value: "TW", label: "Taiwan", continent: "Major Asian Markets" },
  { value: "TH", label: "Thailand", continent: "Major Asian Markets" },
  { value: "ID", label: "Indonesia", continent: "Major Asian Markets" },
  { value: "VN", label: "Vietnam", continent: "Major Asian Markets" },

  // AMERICAS
  { value: "MX", label: "Mexico", continent: "Americas" },
  { value: "BR", label: "Brazil", continent: "Americas" },
  { value: "AR", label: "Argentina", continent: "Americas" },
  { value: "CL", label: "Chile", continent: "Americas" },
  { value: "CO", label: "Colombia", continent: "Americas" },

  // MIDDLE EAST
  { value: "AE", label: "United Arab Emirates", continent: "Middle East" },
  { value: "SA", label: "Saudi Arabia", continent: "Middle East" },
  { value: "IL", label: "Israel", continent: "Middle East" },

  // REST OF WORLD (catch-all)
  { value: "OTHER", label: "Rest of World", continent: "Rest of World" },
];

// All 195+ countries mapped to their display country
// This allows search to work for any country name
export const COUNTRY_SEARCH_MAP: Record<string, string> = {
  // Primary English-Speaking (already listed)
  "united states": "US",
  usa: "US",
  "north america": "US",
  "united kingdom": "GB",
  uk: "GB",
  britain: "GB",
  "great britain": "GB",
  england: "GB",
  scotland: "GB",
  wales: "GB",
  "northern ireland": "GB",
  canada: "CA",
  australia: "AU",
  "new zealand": "NZ",
  eire: "IE",
  espana: "ES",
  ireland: "IE",
  "south africa": "ZA",

  // Large English-Speaking (already listed)
  india: "IN",
  philippines: "PH",
  nigeria: "NG",
  pakistan: "PK",
  singapore: "SG",
  malaysia: "MY",
  "hong kong": "HK",
  kenya: "KE",
  ghana: "GH",

  // Major European Markets (already listed)
  germany: "DE",
  france: "FR",
  spain: "ES",
  italy: "IT",
  netherlands: "NL",
  nederland: "NL",
  belgie: "BE",
  belgië: "BE",
  holland: "NL",
  sweden: "SE",
  norway: "NO",
  denmark: "DK",
  finland: "FI",
  switzerland: "CH",
  austria: "AT",
  belgium: "BE",
  suise: "CH",
  suïsse: "CH",
  italia: "IT",
  italie: "IT",
  portugal: "PT",

  // Major Asian Markets (already listed)
  japan: "JP",
  "south korea": "KR",
  korea: "KR",
  china: "CN",
  taiwan: "TW",
  thailand: "TH",
  indonesia: "ID",
  vietnam: "VN",

  // Americas (already listed)
  mexico: "MX",
  brazil: "BR",
  argentina: "AR",
  chile: "CL",
  colombia: "CO",

  // Middle East (already listed)
  uae: "AE",
  "united arab emirates": "AE",
  emirates: "AE",
  dubai: "AE",
  "saudi arabia": "SA",
  saudi: "SA",
  israel: "IL",

  // REST OF WORLD - All other countries map to OTHER
  // Europe
  poland: "OTHER",
  "czech republic": "OTHER",
  czechia: "OTHER",
  romania: "OTHER",
  hungary: "OTHER",
  bulgaria: "OTHER",
  greece: "OTHER",
  croatia: "OTHER",
  slovenia: "OTHER",
  slovakia: "OTHER",
  estonia: "OTHER",
  latvia: "OTHER",
  lithuania: "OTHER",
  iceland: "OTHER",
  luxembourg: "OTHER",
  malta: "OTHER",
  cyprus: "OTHER",
  albania: "OTHER",
  serbia: "OTHER",
  bosnia: "OTHER",
  montenegro: "OTHER",
  "north macedonia": "OTHER",
  macedonia: "OTHER",
  moldova: "OTHER",
  ukraine: "OTHER",
  belarus: "OTHER",
  russia: "OTHER",
  turkey: "OTHER",

  // Asia Pacific
  bangladesh: "OTHER",
  "sri lanka": "OTHER",
  nepal: "OTHER",
  myanmar: "OTHER",
  burma: "OTHER",
  cambodia: "OTHER",
  laos: "OTHER",
  mongolia: "OTHER",
  kazakhstan: "OTHER",
  uzbekistan: "OTHER",
  kyrgyzstan: "OTHER",
  tajikistan: "OTHER",
  turkmenistan: "OTHER",
  afghanistan: "OTHER",
  "papua new guinea": "OTHER",
  fiji: "OTHER",
  "new caledonia": "OTHER",
  "solomon islands": "OTHER",
  vanuatu: "OTHER",
  samoa: "OTHER",
  tonga: "OTHER",
  maldives: "OTHER",
  bhutan: "OTHER",
  brunei: "OTHER",
  "timor-leste": "OTHER",
  "east timor": "OTHER",

  // Africa
  egypt: "OTHER",
  morocco: "OTHER",
  tunisia: "OTHER",
  algeria: "OTHER",
  libya: "OTHER",
  ethiopia: "OTHER",
  tanzania: "OTHER",
  uganda: "OTHER",
  rwanda: "OTHER",
  burundi: "OTHER",
  senegal: "OTHER",
  "ivory coast": "OTHER",
  cameroon: "OTHER",
  angola: "OTHER",
  mozambique: "OTHER",
  zimbabwe: "OTHER",
  zambia: "OTHER",
  botswana: "OTHER",
  namibia: "OTHER",
  mali: "OTHER",
  niger: "OTHER",
  chad: "OTHER",
  sudan: "OTHER",
  "south sudan": "OTHER",
  somalia: "OTHER",
  djibouti: "OTHER",
  eritrea: "OTHER",
  malawi: "OTHER",
  madagascar: "OTHER",
  mauritius: "OTHER",
  seychelles: "OTHER",
  comoros: "OTHER",
  benin: "OTHER",
  togo: "OTHER",
  "burkina faso": "OTHER",
  guinea: "OTHER",
  "sierra leone": "OTHER",
  liberia: "OTHER",
  gambia: "OTHER",
  "guinea-bissau": "OTHER",
  "equatorial guinea": "OTHER",
  gabon: "OTHER",
  congo: "OTHER",
  "democratic republic of congo": "OTHER",
  drc: "OTHER",
  "central african republic": "OTHER",
  lesotho: "OTHER",
  eswatini: "OTHER",
  swaziland: "OTHER",

  // Americas
  peru: "OTHER",
  venezuela: "OTHER",
  ecuador: "OTHER",
  bolivia: "OTHER",
  paraguay: "OTHER",
  uruguay: "OTHER",
  guyana: "OTHER",
  suriname: "OTHER",
  "french guiana": "OTHER",
  "costa rica": "OTHER",
  panama: "OTHER",
  nicaragua: "OTHER",
  honduras: "OTHER",
  "el salvador": "OTHER",
  guatemala: "OTHER",
  belize: "OTHER",
  jamaica: "OTHER",
  "trinidad and tobago": "OTHER",
  trinidad: "OTHER",
  tobago: "OTHER",
  bahamas: "OTHER",
  barbados: "OTHER",
  haiti: "OTHER",
  "dominican republic": "OTHER",
  cuba: "OTHER",
  "puerto rico": "OTHER",
  grenada: "OTHER",
  "saint lucia": "OTHER",
  "saint vincent": "OTHER",
  antigua: "OTHER",
  dominica: "OTHER",
  "saint kitts": "OTHER",

  // Middle East
  qatar: "OTHER",
  kuwait: "OTHER",
  bahrain: "OTHER",
  oman: "OTHER",
  yemen: "OTHER",
  jordan: "OTHER",
  lebanon: "OTHER",
  syria: "OTHER",
  iraq: "OTHER",
  iran: "OTHER",
  palestine: "OTHER",
};
