name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    name: Typecheck, Lint, Unit Tests
    runs-on: ubuntu-latest
    environment: ci
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Typecheck
        run: pnpm run typecheck
        env:
          NODE_ENV: test
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}
          APP_ENCRYPTION_KEY: ${{ secrets.APP_ENCRYPTION_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ vars.GOOGLE_REDIRECT_URI }}
          FEATURE_GOOGLE_GMAIL_RO: ${{ vars.FEATURE_GOOGLE_GMAIL_RO }}
          FEATURE_GOOGLE_CALENDAR_RO: ${{ vars.FEATURE_GOOGLE_CALENDAR_RO }}
          FEATURE_GOOGLE_DRIVE: ${{ vars.FEATURE_GOOGLE_DRIVE }}
          API_RATE_LIMIT_PER_MIN: ${{ vars.API_RATE_LIMIT_PER_MIN }}
          API_MAX_JSON_BYTES: ${{ vars.API_MAX_JSON_BYTES }}

      - name: Lint
        run: pnpm run lint

      - name: Unit tests (Vitest)
        run: pnpm run test
        env:
          NODE_ENV: test
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}
          APP_ENCRYPTION_KEY: ${{ secrets.APP_ENCRYPTION_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ vars.GOOGLE_REDIRECT_URI }}
          FEATURE_GOOGLE_GMAIL_RO: ${{ vars.FEATURE_GOOGLE_GMAIL_RO }}
          FEATURE_GOOGLE_CALENDAR_RO: ${{ vars.FEATURE_GOOGLE_CALENDAR_RO }}
          FEATURE_GOOGLE_DRIVE: ${{ vars.FEATURE_GOOGLE_DRIVE }}
          API_RATE_LIMIT_PER_MIN: ${{ vars.API_RATE_LIMIT_PER_MIN }}
          API_MAX_JSON_BYTES: ${{ vars.API_MAX_JSON_BYTES }}

  e2e:
    name: E2E (Playwright)
    runs-on: ubuntu-latest
    environment: ci
    timeout-minutes: 30
    needs: build-and-test
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install deps
        run: pnpm install --frozen-lockfile

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Note: E2E will skip DB-coupled tests if DATABASE_URL is not present
      - name: Run E2E tests
        run: pnpm run e2e
        env:
          NODE_ENV: test
          NEXT_PUBLIC_SUPABASE_URL: ${{ vars.NEXT_PUBLIC_SUPABASE_URL }}
          NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_DEFAULT_KEY }}
          APP_ENCRYPTION_KEY: ${{ secrets.APP_ENCRYPTION_KEY }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ vars.GOOGLE_REDIRECT_URI }}
          FEATURE_GOOGLE_GMAIL_RO: ${{ vars.FEATURE_GOOGLE_GMAIL_RO }}
          FEATURE_GOOGLE_CALENDAR_RO: ${{ vars.FEATURE_GOOGLE_CALENDAR_RO }}
          FEATURE_GOOGLE_DRIVE: ${{ vars.FEATURE_GOOGLE_DRIVE }}
          API_RATE_LIMIT_PER_MIN: ${{ vars.API_RATE_LIMIT_PER_MIN }}
          API_MAX_JSON_BYTES: ${{ vars.API_MAX_JSON_BYTES }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
